version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: d3-scale
    versions:
    - 3.2.3
    - 3.2.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: react-day-picker
    versions:
    - 7.4.8
  - dependency-name: handlebars
    versions:
    - 4.7.6
